config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
    resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
        resources :book_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :index] do
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :book_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    book = Book.find(params[:book_id])
    redirect_to book_path(book)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render "index"
    end
  end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @user_template = User.find(current_user.id)
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user #URLを入力しても画面に飛ばせない
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render "edit"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    book = book
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
      if @user == current_user
        render "edit"
      else
        redirect_to user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'successfully updated!'
    else
      render "edit"
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = User.find(current_user.id)
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_footer.html.erb
<footer>
  <div class = "container mt-5">
    <div class = "row">
      <div class = "mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/_header.html.erb
<header>
  <nav class="nabvar navbar-expand-lg navbar-dark bg-dark">
    <a class = "navbar-brand" href="/">
      <span>Bookers</span>
    </a>
    <button class = "navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class = "navbar-toggler-icon"></span>
    </button>
    <div class = "collapse nabvar-collapse" id="navbarNavDropdown">
      <ul class = "nabvar-nav ml-auto">
        <% if user_signed_in? %>
        <li>
          <a class = "fas fa-home nav-link text-light" href="/user">Home</a>
        </li>
        <li>
          <a class = "fas fa-users nav-linktext-light" href="/users">Users</a>
        </li>
        <li>
          <a class = "fas fa-book-open nav-linktext-light" href="/books">Books</a>
        </li>
        <li>
          <a class = "fas fa-sign-out-alt nav-linktext-light" rel ="nofollow" data-method="delete" href="/users/sign_out">Log out</a>
        </li>
        <% else %>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/books/_list.html.erb
<% books.each do |book| %>
<div>
  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <%= link_to book_path(book.id) do %>
    <p>title：<%= book.title %></p>
  <% end %>
  <p>opinion：<%= book.body %></p>
</div>
<% end %>
<%= paginate books %>

app/views/books/_new_book.html.erb
<h2>New book</h2>

<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>

<% end %>

app/views/books/edit.html.erb
<div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
</div>

<div>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">

      <h2>Editing Book</h2>

      <!--エラーメッセージ-->
      <div class="error">
        <div class="error_messege">
          <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>

      <!--投稿編集フォーム-->
      <%= form_with model:@book, local:true do |f| %>
        <div class="field row">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="field row">
          <%= f.label :body %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="actions row">
          <%= f.submit class: "btn btn-primary form-control" %>
        </div>

        <div class="link">
          <%= link_to "Show", book_path(@book.id) %>
          <%= "  |  " %>
          <%= link_to "Back", books_path %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<body>
  <div class="container">
    <div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>
    <div class = "row">
      <div class="col-md-3">
        <%= render 'users/user_info', user: @user %>
        <%= render 'books/new_book', book: @book %>
      </div>
      <div class = "col-md-8 offset-md-1">
        <header>
          <h1>Books</h1>
        </header>
        <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><br>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
        <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
      </td>
      <% if book.favorited_by?(current_user) %>
        <td>
          <%= link_to book_favorites_path(book), method: :delete do %>
            <p><i class="fas fa-heart"></i></p><%= book.favorites.count %> いいね
          <% end %>
        </td>
      <% else %>
        <td>
          <%= link_to book_favorites_path(book), method: :post do %>
            <p><i class="far fa-heart"></i></p><%= book.favorites.count %> いいね
          <% end %>
        </td>
      <% end %>
    </tr>
    <% end %>

  </tbody>
</table>
      </div>
    </div>
  </div>
</body>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
</div>

<body>
  <div class="container">
    <div class = "row">
      <div class="col-md-3">
        <%= render 'users/user_info', user: @user %>
        <%= render 'books/new_book', book: @newbook %>
      </div>

      <div class = "col-md-8 offset-md-1">
        <header>
          <h1>Book detail</h1>
        </header>

        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book.id)%>
              </td>
              <td><%= @book.body %></td>
              <td>
                <p>コメント件数：<%= @book.book_comments.count %></p>
              </td>
              <% if @book.user_id == current_user.id && user_signed_in?%>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "edit-button" %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm:  "Are you sure?"}, class: "destroy-button" %></td>
              <% end %>
              <% if @book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <p><i class="fas fa-heart"></i></p><%= @book.favorites.count %> いいね
                  <% end %>
                </td>
                <% else %>
                <td>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <p><i class="far fa-heart"></i></p><%= @book.favorites.count %> いいね
                  <% end %>
                </td>
              <% end %>
            </tr>
            </tbody>
        </table>
        <div class="row">
          <% @book.book_comments.each do |book_comment| %>
          <div class="col-md-3">
            <%= link_to user_path(book_comment.user) do %>
            <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><br>
            <%= book_comment.user.name %>
            <% end %>
          </div>
          <div class ="col-md-8 offset-md-1">
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm:  "Are you sure?"}, class: "destroy-button" %>
            <% end %>
          </div>
          <% end %>
        </div>

        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <%= f.text_area :comment, rows:'5',placeholder: "コメントを送信" %>
        <%= f.submit "コメントを送信" %>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/homes/about.html.erb
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
<main>
        <p id="notice">Signed out successfully.</p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/"><span>Bookers</span></a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
                  <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li>
          <%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
        </li>
        <li>
          <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
        </li>
        <li>
          <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
        </li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light"  %>
        </li>
        <% else %>
        <li>
          <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
        </li>
         <li>
          <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light"  %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
        </li>
        <li>
          <%= link_to "Login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>

  <footer>
    <div class = "container mt-5">
      <div class = "row">
        <div class = "mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%= user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
  <div class="row">
    <%= link_to edit_user_path(user.id) do %>
      <i class="btn btn-outline-secondary btn-block fas fa-user-cog " ></i>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
</div>

<div>
  <div class="container">
      <h2>User info</h2>


      <p id="notice">
        <%= notice %>
      </p>
      <div class="error">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="field row">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="field row">
          <%= f.label :image %>
          <%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %>
        </div>
        <div class="field row">
          <%= f.label :introduction %>
          <%= f.text_area :introduction %>
        </div>
        <div class="actions row">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>


  </div>
</div>

app/views/users/index.html.erb
<div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
</div>

<body>
  <div class="container">
    <div class = "row">
      <div class="col-md-3">
        <%= render 'users/user_info', user: @user %>
        <%= render 'books/new_book', book: @book %>
      </div>
      <div class = "col-md-8 offset-md-1">
        <header>
          <h1>Users</h1>
        </header>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<div class="messege">
  <p id="notice"> <!--サクセスメッセージ-->
    <%= notice %>
  </p>
</div>

<body>
  <div class="container">
    <div class = "row">
      <div class="col-md-3">
        <%= render 'users/user_info', user: @user %>
        <%= render 'books/new_book', book: @book %>
      </div>
      <div class = "col-md-8 offset-md-1">
        <header>
          <h1>Books</h1>
        </header>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>title</th>
              <th>opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><br>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>

              <td>
                <p>コメント件数：<%= book.book_comments.count %></p>
              </td>
              <% if book.user_id == current_user.id && user_signed_in?%>
                <td><%= link_to "Edit", edit_book_path(book.id), class: "edit-button" %></td>
                <td><%= link_to "Destroy", book_path(book), method: :delete, data: {confirm:  "Are you sure?"}, class: "destroy-button" %></td>
              <% end %>
              <% if book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <p><i class="fas fa-heart"></i></p><%= book.favorites.count %> いいね
                  <% end %>
                </td>
                <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <p><i class="far fa-heart"></i></p><%= book.favorites.count %> いいね
                  <% end %>
                </td>
              <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>